# Site
repository: sproogen/resume-theme
favicon: images/hyungwoo.png

# Content configuration version
version: 2

# Personal info
name: YooHyungWoo
title: Junior Frontend Developer
email: db6194@gmail.com
website: www.github.com/yoohyungwoo

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  YooHyungWoo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-blog
  url:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/hyungwoo.png
about_content: | # this will include new lines to allow paragraphs
  ## 현재에 안주하지 않고 항상 개발하는 개발자 입니다.
  <br/>
  비전공자로서 항상 끊임없는 노력과 공부를 하며 개발을 하고 있는 유형우 입니다. <br/>
  새로운 기술에 대해 항상 흥미와 관심을 보이며 무엇이든 먼저 해보는 성격입니다.<br/>
  주로 <mark>Vue.js</mark>를 사용하며 개발하며 언어는 <mark>JavaScript</mark>, <mark>TypeScript</mark> 등을 사용하고 있습니다.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: ABACUS SW
        link: http://www.iabacus.co.kr/iabacus/
        link_text: iabacus.co.kr
        sub_title: Frontend Developer
        caption: 2022.01 ~ Present
        quote: >
        description: | # this will include new lines to allow paragraphs
          - 회사 프로젝트에서 Frontend 개발을 업무를 진행하고 있으며 
          주로 Vue.js로 개발을 진행 합니다.
      - layout: left
        title: 컴퓨터 활용능력 2급
        caption: 2021.02
        quote: >
        description: | # this will include new lines to allow paragraphs
          - 2021.02 자격증 취득
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한국방송통신대학교
        caption: 2023 ~ Present
        sub_title: 편입
        quote: >
        description: |
          - 컴퓨터과학과 재학중
      - layout: left
        title: 에이콘아카데미(강남)
        caption: 2021.03 ~ 2021.09
        quote: >
        description: |
          - Web기반 프론트엔드 개발자 양성과정 [NCS] 수료
      - layout: left
        title: 김포대학교
        caption: 2017 ~ 2021
        sub_title: 전문학사
        quote: >
        description: |
          - 항공관광경영학과 졸업
      - layout: left
        title: 용산고등학교
        caption: 2014 ~ 2017
        quote: >
        description: |
         - 졸업
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
